sources:
  - Moderustic-Light.vfc
  - Moderustic-Regular.vfc
  - Moderustic-Medium.vfc
  - Moderustic-SemiBold.vfc
  - Moderustic-Bold.vfc
  - Moderustic-ExBold.vfc
axisOrder:
  - wght
  - norm
familyName: Moderustic
